### ISSUE TITLE
Where to download the 'sugarbeet', 'weed' dataset ?

### ISSUE THREAD

**Issue by dragen1860** [jmpap/YOLOV2-Tensorflow-2.0#1]
Dear author:
  thanks for your great yolo example.
  I wonder where to download the toy dataset: sugarbeet', 'weed'. I google it and can not find the download link? thank you.

**Comment by jmpap** [comment]
Thank you for your positive appreciation. There is no public dataset because I built it myself. I just added the test and training set to the repository.

**Comment by dragen1860** [comment]
yes, it helps. Thank you.
