### ISSUE TITLE
train_annot_folder

### ISSUE THREAD

**Issue by nbincyc** [jmpap/YOLOV2-Tensorflow-2.0#10]
hello. I am new to this whole AI thing. I am currently working on a project similar to this. I Would really like your help. I am not getting this " contains annotations in PASCAL VOC format (one xml file for each image)". I have my own dataset of images. What is this PASCAL VOC format? should I need to create one xml file of my very own image?  If yes, what should I put in it? I'm really clueless. Please help.

**Comment by jmpap** [comment]
Hi, yes, you must create an xml file for each image. This xml file contains the characteristics of each object present in the image: bounding box coordinates, class of the object. You can see some examples in the data/train/annotation folder of this repository.

**Comment by nbincyc** [comment]
> Hi, yes, you must create an xml file for each image. This xml file contains the characteristics of each object present in the image: bounding box coordinates, class of the object. You can see some examples in the data/train/annotation folder of this repository.

thank you so much!
