### ISSUE TITLE
Permission error no 13

### ISSUE THREAD

**Issue by nbincyc** [jmpap/YOLOV2-Tensorflow-2.0#11]
Hello! Thank you so much for such a wonderful code and solving my previous error before. I'm getting this error and I'm trying it to solve for the past few days. I'm running my JUPYTER NOTEBOOK via ANACONDA VIRTUAL ENVIRONMENT as an ADMIN. I've PYTHON 3.7.7 and TENSORFLOW 2.1.0. WINDOWS 10 X64 bit with no GPU. Would really appreciate your help. Thank you so much for your time.
![Capture 2](https://user-images.githubusercontent.com/49716001/87852674-a2c2ca80-c921-11ea-9c33-1eea325f984b.JPG)
![Capture](https://user-images.githubusercontent.com/49716001/87852675-a48c8e00-c921-11ea-9d94-e15c4b59f6fa.JPG)

**Comment by jmpap** [comment]
Hi, this seems to be a permission issue on your folders. I can not say more.

**Comment by nbincyc** [comment]
> Hi, this seems to be a permission issue on your folders. I can not say more.
Hello! Thank You so much for your reply. I solved the issue.
