### ISSUE TITLE
i am not able to run the training part it shows some error of adam optimizer

### ISSUE THREAD

**Issue by ashu2496** [jmpap/YOLOV2-Tensorflow-2.0#2]
This is the error at the end
var and grad do not have the same shape[32] [3,3,32,64] [Op:ResourceApplyAdam] 
from optimizer.apply_gradients(zip(grads, model.variables)) call from train function.

I am using tensorflow v2, and just run your notebook file as it is after downloading weight file.

**Comment by jmpap** [comment]
Notebook corrected :
`model.variables` replaced by `model.trainable_variables`

**Comment by ashu2496** [comment]
Thank you, that worked, but i need to reduce batch size to 4 in order to train on single GTX 1060 Max Q or else it gives resource exhaust error, any other suggestions will be appreciated.

Also if i want to change input size(608*608)or less, will i have to use same pre-trained weights file?

**Comment by jmpap** [comment]
Yes, you can reduce batch size to avoid memory error.

If you have your own dataset, you can use a 608 * 608 image with yolo-weights because the yolo model does not depend on the input size. In this case, you must use the grid size parameter = 19 (grid size = input size / 32).
