### ISSUE TITLE
Using pictures that are not all the same size

### ISSUE THREAD

**Issue by puppol** [jmpap/YOLOV2-Tensorflow-2.0#3]
Hey there! I'm attempting to use my own dataset where the images are both non-square and varying in dims. Is there a way to modify your code to allow for this?
Thanks so much in advance!

**Comment by jmpap** [comment]
Hi, no you can't use differents image size in the same dataset but you can change the function 'parse_function' (part '3.1. Dataset') to resize your images to the same size :

`x_img = tf.image.resize(x_img, SIZE)`

**Comment by puppol** [comment]
Okay, thanks! I assume then I will need to resize the labels as well?

**Comment by jmpap** [comment]
Yes, you need to resize labels (box dimensions), but perhaps it's a better idea to resize images and labels before using this notebook.
