### ISSUE TITLE
Error while using custom dataset

### ISSUE THREAD

**Issue by Mshaoor** [jmpap/YOLOV2-Tensorflow-2.0#4]
Hi 
I got this error in section [3.3. Process data to YOLO prediction]. I use my own dataset with all images that have size [720 x 1280] with only one class but I got this error so please help me in this regard. I can't understand the issue.

waiting for your kind response

this is the error 
 ValueError: Dimension size must be evenly divisible by 225280 but is 460800 for '{{node model_2/space_to_depth_2/Reshape}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32](model_2/leaky_re_lu_64/LeakyRelu, model_2/space_to_depth_2/Reshape/shape)' with input shapes: [2,45,80,64], [6] and with input tensors computed as partial shapes: input[1] = [?,22,2,40,2,64].

![Screenshot from 2020-04-14 07-48-02](https://user-images.githubusercontent.com/36337219/79180984-c529e100-7e24-11ea-95fb-e67e92e30394.png)

**Comment by jmpap** [comment]
Hi,
The output shape of the model is equal to the input shape divided by 32. The size of your image must therefore be divisible by 32, which is not the case for 720. You can resize (or crop) your images and annotations before training.
