### ISSUE TITLE
ResourceExhaustedError: OOM when allocating tensor with shape[5,32,512,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:FusedBatchNormGradV3] Error occured

### ISSUE THREAD

**Issue by 201810788** [jmpap/YOLOV2-Tensorflow-2.0#7]
Epoch 0 :
----
---------------------------------------------------------------------------
ResourceExhaustedError                    Traceback (most recent call last)
<ipython-input-28-ad12deb28033> in <module>
----> 1 results = train(EPOCHS, model, train_gen, val_gen, 10, 2, 'training_1')
      2 
      3 plt.plot(results[0])
      4 plt.plot(results[1])

<ipython-input-27-7b09cc17cb6b> in train(epochs, model, train_dataset, val_dataset, steps_per_epoch_train, steps_per_epoch_val, train_name)
     49         for batch_idx in range(steps_per_epoch_train):
     50             img, detector_mask, matching_true_boxes, class_one_hot, true_boxes =  next(train_dataset)
---> 51             loss, _, grads = grad(model, img, detector_mask, matching_true_boxes, class_one_hot, true_boxes)
     52             optimizer.apply_gradients(zip(grads, model.trainable_variables))
     53             epoch_loss.append(loss)

<ipython-input-26-28479602bd97> in grad(model, img, detector_mask, matching_true_boxes, class_one_hot, true_boxes, training)
      4         y_pred = model(img, training)
      5         loss, sub_loss = yolov2_loss(detector_mask, matching_true_boxes, class_one_hot, true_boxes, y_pred)
----> 6     return loss, sub_loss, tape.gradient(loss, model.trainable_variables)
      7 
      8 # save weights

c:\users\muho\anaconda3\envs\traffic_light\lib\site-packages\tensorflow_core\python\eager\backprop.py in gradient(self, target, sources, output_gradients, unconnected_gradients)
   1012         output_gradients=output_gradients,
   1013         sources_raw=flat_sources_raw,
-> 1014         unconnected_gradients=unconnected_gradients)
   1015 
   1016     if not self._persistent:

c:\users\muho\anaconda3\envs\traffic_light\lib\site-packages\tensorflow_core\python\eager\imperative_grad.py in imperative_grad(tape, target, sources, output_gradients, sources_raw, unconnected_gradients)
     74       output_gradients,
     75       sources_raw,
---> 76       compat.as_str(unconnected_gradients.value))

c:\users\muho\anaconda3\envs\traffic_light\lib\site-packages\tensorflow_core\python\eager\backprop.py in _gradient_function(op_name, attr_tuple, num_inputs, inputs, outputs, out_grads, skip_input_indices)
    136     return [None] * num_inputs
    137 
--> 138   return grad_fn(mock_op, *out_grads)
    139 
    140 

c:\users\muho\anaconda3\envs\traffic_light\lib\site-packages\tensorflow_core\python\ops\nn_grad.py in _FusedBatchNormV3Grad(op, *grad)
    924 @ops.RegisterGradient("FusedBatchNormV3")
    925 def _FusedBatchNormV3Grad(op, *grad):
--> 926   return _BaseFusedBatchNormGrad(op, 2, *grad)
    927 
    928 

c:\users\muho\anaconda3\envs\traffic_light\lib\site-packages\tensorflow_core\python\ops\nn_grad.py in _BaseFusedBatchNormGrad(op, version, *grad)
    888     if version == 2:
    889       args["reserve_space_3"] = op.outputs[5]
--> 890     return grad_fun(**args)
    891   else:
    892     pop_mean = op.inputs[3]

c:\users\muho\anaconda3\envs\traffic_light\lib\site-packages\tensorflow_core\python\ops\gen_nn_ops.py in fused_batch_norm_grad_v3(y_backprop, x, scale, reserve_space_1, reserve_space_2, reserve_space_3, epsilon, data_format, is_training, name)
   4341       else:
   4342         message = e.message
-> 4343       _six.raise_from(_core._status_to_exception(e.code, message), None)
   4344   # Add nodes to the TensorFlow graph.
   4345   if epsilon is None:

c:\users\muho\anaconda3\envs\traffic_light\lib\site-packages\six.py in raise_from(value, from_value)

ResourceExhaustedError: OOM when allocating tensor with shape[5,32,512,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:FusedBatchNormGradV3]

I tried to change batch size and epoch, but the error are still occured...

**Comment by jmpap** [comment]
Hello, you can try to reduce batch size until you have enough memory.

**Comment by abhinavmaurya747** [comment]
My system configuration is :- 8GB RAM, 4GB Dedicated Graphics, GTX 1050Ti GPU
I was facing the same problem so i reduced the batch size to 2.

Surprisingly it worked.
Maybe tweaking with the same can result better.

If there's any alternative way, let me know...
