### ISSUE TITLE
getting error in generating dateset

### ISSUE THREAD

**Issue by abhinavmaurya747** [jmpap/YOLOV2-Tensorflow-2.0#8]
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
~\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\eager\context.py in execution_mode(mode)
   1985       ctx.executor = executor_new
-> 1986       yield
   1987     finally:

~\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\data\ops\iterator_ops.py in _next_internal(self)
    654             output_types=self._flat_output_types,
--> 655             output_shapes=self._flat_output_shapes)
    656 

~\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\ops\gen_dataset_ops.py in iterator_get_next(iterator, output_types, output_shapes, name)
   2362     except _core._NotOkStatusException as e:
-> 2363       _ops.raise_from_not_ok_status(e, name)
   2364   # Add nodes to the TensorFlow graph.

~\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\ops.py in raise_from_not_ok_status(e, name)
   6652   # pylint: disable=protected-access
-> 6653   six.raise_from(core._status_to_exception(e.code, message), None)
   6654   # pylint: enable=protected-access

C:\ProgramData\Anaconda3\lib\site-packages\six.py in raise_from(value, from_value)

NotFoundError: NewRandomAccessFile failed to Create/Open: Opana-7.jpg : The system cannot find the file specified.
; No such file or directory
	 [[{{node ReadFile}}]] [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
<ipython-input-150-7b7ebf6e6560> in <module>
     24         break
     25 
---> 26 test_dataset(train_dataset)
     27 train_dataset

<ipython-input-150-7b7ebf6e6560> in test_dataset(dataset)
      2 
      3 def test_dataset(dataset):
----> 4     for batch in dataset:
      5         img = batch[0][0]
      6         label = batch[1][0]

~\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\data\ops\iterator_ops.py in __next__(self)
    629 
    630   def __next__(self):  # For Python 3 compatibility
--> 631     return self.next()
    632 
    633   def _next_internal(self):

~\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\data\ops\iterator_ops.py in next(self)
    668     """Returns a nested structure of `Tensor`s containing the next element."""
    669     try:
--> 670       return self._next_internal()
    671     except errors.OutOfRangeError:
    672       raise StopIteration

~\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\data\ops\iterator_ops.py in _next_internal(self)
    659         return self._element_spec._from_compatible_tensor_list(ret)  # pylint: disable=protected-access
    660       except AttributeError:
--> 661         return structure.from_compatible_tensor_list(self._element_spec, ret)
    662 
    663   @property

C:\ProgramData\Anaconda3\lib\contextlib.py in __exit__(self, type, value, traceback)
    128                 value = type()
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
    132                 # Suppress StopIteration *unless* it's the same exception that

~\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\eager\context.py in execution_mode(mode)
   1987     finally:
   1988       ctx.executor = executor_old
-> 1989       executor_new.wait()
   1990 
   1991 

~\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\eager\executor.py in wait(self)
     65   def wait(self):
     66     """Waits for ops dispatched in this executor to finish."""
---> 67     pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
     68 
     69   def clear_error(self):

NotFoundError: NewRandomAccessFile failed to Create/Open: Opana-7.jpg : The system cannot find the file specified.
; No such file or directory
	 [[{{node ReadFile}}]]

**Comment by abhinavmaurya747** [comment]
I have modified the parse_annotation() function so that I can parse the data from csv_files as my annotation data is present in a csv file.
All the working of the parse_annotation() is kept identical and also it returns the same output as required.
But Still I am getting error.

**Comment by abhinavmaurya747** [comment]
I am training for 3 classes. Here are the parameters list. Help me if there's something wrong.

# Parameters

LABELS           = ('Radome', 'MeshAntenna','OTHR')
IMAGE_H, IMAGE_W = 512, 512
GRID_H,  GRID_W  = 16, 16 # GRID size = IMAGE size / 32
BOX              = 5
CLASS            = len(LABELS)
SCORE_THRESHOLD  = 0.5
IOU_THRESHOLD    = 0.45
ANCHORS          = [0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828]

TRAIN_BATCH_SIZE = 2
VAL_BATCH_SIZE   = 2
EPOCHS           = 2

LAMBDA_NOOBJECT  = 1
LAMBDA_OBJECT    = 5
LAMBDA_CLASS     = 1
LAMBDA_COORD     = 1

max_annot        = 0

**Comment by jmpap** [comment]
Hello, it seems that dataset generator can't find your image files. Did you correctly set your images folder path?

**Comment by abhinavmaurya747** [comment]
Thanks for your help. I have resolved the issue. Setting the path works fine.
