### ISSUE TITLE
Getting error while running the test generator pipeline

### ISSUE THREAD

**Issue by abhinavmaurya747** [jmpap/YOLOV2-Tensorflow-2.0#9]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-27-853e0e3e6a27> in <module>
      4 
      5 # batch
----> 6 img, detector_mask, matching_true_boxes, class_one_hot, true_boxes = next(train_gen)
      7 
      8 # y

<ipython-input-25-7ef5c0644a9d> in ground_truth_generator(dataset)
     38                                                                                            ANCHORS,
     39                                                                                            IMAGE_W,
---> 40                                                                                            IMAGE_H)
     41             batch_matching_true_boxes.append(one_matching_true_boxes)
     42             batch_detector_mask.append(one_detector_mask)

<ipython-input-24-cd28b6ca1bbc> in process_true_boxes(true_boxes, anchors, image_width, image_height)
     65                 x_coord = np.floor(x).astype('int')
     66                 y_coord = np.floor(y).astype('int')
---> 67                 detector_mask[y_coord, x_coord, best_anchor] = 1
     68                 yolo_box = np.array([x, y, w, h, box[4]])
     69                 matching_true_boxes[y_coord, x_coord, best_anchor] = yolo_box

IndexError: index 31 is out of bounds for axis 0 with size 16

In my dataset the image with the maximum coordinates (boxes) is 16. So the shape of boxes is (392, 17, 5) for training set and (79, 17, 5) for the test set.

**Comment by jmpap** [comment]
Hi, did you change Yolo settings at the start of the notebook?
LABELS, IMAGE_H, IMAGE_W, GRID_H,  GRID_W...
